### PR TITLE
Add an overview of all available SDKs

### PR DESCRIPTION
**Pull request by turbolent**
It would be nice to integrate this into the docs, maybe as a link in the left sidebar.

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by githubwei** [comment]
@turbolent I was wondering if we need to add a disclaimer clarifying many SDKs are being maintained by the community, as volunteers, so before using developers should be aware there is no guarantee in terms of continued development and support. 

That way we avoid the issue of some developers complaining they wasted their efforts in building an app with the assumption of the SDK being always available and maintained, especially with breaking changes.

**Comment by turbolent** [comment]
@githubwei This is true for any open-source project, so I'd let such considerations be up to the user

**Comment by turbolent** [comment]
@psiemens @10thfloor any thoughts?

**Comment by srinjoyc** [comment]
I'd add here as well that I'd agree with @githubwei  => We should point out which repos have complete documentation and is "recommended" by us. With so many choices, it might be easy to assume there is equal support from the community which is not quite true. Their experience could end quite quickly if they get frustrated and make the wrong choice here.

**Review by srinjoyc — APPROVED** [review]

**Review by 10thfloor — APPROVED** [review]

**Pull request merged**
